# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: hyperliquid
networks:
  - id: 645749
    start_block: 4107927
    contracts:
      - name: MToken
        address:
          - 0x866A2BF4E572CbcF37D5071A7a58503Bfb36be1b
        handler: src/EventHandlers.ts
        events:
          - event: IndexUpdated(uint128 indexed index)
          - event: StartedEarning(address indexed account)
          - event: StoppedEarning(address indexed account)
          - event: Transfer(address indexed sender, address indexed recipient, uint256 amount)
      - name: USDHL
        address:
          - 0xb50A96253aBDF803D85efcDce07Ad8becBc52BD5
        handler: src/EventHandlers.ts
        events:
          - event: Transfer(address indexed from, address indexed to, uint256 value)
          - event: YieldClaimed(uint256 yield)
          - event: YieldRecipientSet(address indexed newRecipient)
unordered_multichain_mode: true
